[package]
name = "string_macros"
description = "Small proc macro library for handling string literals"
version = "1.0.0"
license = "Apache-2.0 OR MIT"
edition = "2021"

[lib]
proc-macro=true

[dependencies]
